# Generated by Django 6.0.3 on 2026-03-25 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_orders_orde_user_id_a87c6f_idx_and_more'),
        ('returns', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='returnrequest',
            index=models.Index(fields=['order'], name='returns_ret_order_i_30fb33_idx'),
        ),
        migrations.AddIndex(
            model_name='returnrequest',
            index=models.Index(fields=['status'], name='returns_ret_status_d3fc8b_idx'),
        ),
    ]
