# Generated by Django 6.0.3 on 2026-03-25 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('products', '0002_product_products_pr_created_52f0d7_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['variant'], name='inventory_i_variant_3983b1_idx'),
        ),
    ]
